// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// robert@callproof.com
// const SUPABASE_URL = "https://rfevteftvvniiuihugfk.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZXZ0ZWZ0dnZuaWl1aWh1Z2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzIwMjEsImV4cCI6MjA2OTY0ODAyMX0.NRzvNPlF8LqsyOWthaAql2M_pwYPxhLO4aZs8u8QEZY";

// sathishait1996@gmail.com
const SUPABASE_URL ="https://qdvusrwnfzqvemwkuwzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdnVzcnduZnpxdmVtd2t1d3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODAzNjksImV4cCI6MjA3MDU1NjM2OX0.3TTZTYW7k1Bj4McX51GLsd0mrhcClSrjGckHGQ2OKPA";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});